[2024-03-13T18:39:13.742+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:05.036670+00:00 [queued]>
[2024-03-13T18:39:13.749+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:05.036670+00:00 [queued]>
[2024-03-13T18:39:13.749+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-13T18:39:13.758+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-13 18:39:05.036670+00:00
[2024-03-13T18:39:13.765+0000] {standard_task_runner.py:60} INFO - Started process 255 to run task
[2024-03-13T18:39:13.768+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-03-13T18:39:05.036670+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp5aok1crf']
[2024-03-13T18:39:13.770+0000] {standard_task_runner.py:88} INFO - Job 108: Subtask inaccurate
[2024-03-13T18:39:13.806+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:05.036670+00:00 [running]> on host b58d4254a693
[2024-03-13T18:39:13.871+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T18:39:05.036670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T18:39:05.036670+00:00'
[2024-03-13T18:39:13.873+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-13T18:39:13.874+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'inaccurate'"]
[2024-03-13T18:39:13.885+0000] {subprocess.py:86} INFO - Output:
[2024-03-13T18:39:13.886+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-13T18:39:13.887+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-13T18:39:13.907+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240313T183905, start_date=20240313T183913, end_date=20240313T183913
[2024-03-13T18:39:13.947+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T18:39:13.970+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
