[2024-03-13T18:39:12.458+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:03.649089+00:00 [queued]>
[2024-03-13T18:39:12.465+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:03.649089+00:00 [queued]>
[2024-03-13T18:39:12.466+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-13T18:39:12.475+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-13 18:39:03.649089+00:00
[2024-03-13T18:39:12.480+0000] {standard_task_runner.py:60} INFO - Started process 247 to run task
[2024-03-13T18:39:12.483+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-03-13T18:39:03.649089+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwk4qzr7v']
[2024-03-13T18:39:12.485+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask inaccurate
[2024-03-13T18:39:12.521+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-03-13T18:39:03.649089+00:00 [running]> on host b58d4254a693
[2024-03-13T18:39:12.584+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T18:39:03.649089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T18:39:03.649089+00:00'
[2024-03-13T18:39:12.586+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-13T18:39:12.587+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'inaccurate'"]
[2024-03-13T18:39:12.597+0000] {subprocess.py:86} INFO - Output:
[2024-03-13T18:39:12.599+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-13T18:39:12.599+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-13T18:39:12.619+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240313T183903, start_date=20240313T183912, end_date=20240313T183912
[2024-03-13T18:39:12.662+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T18:39:12.677+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
