[2024-03-13T18:35:15.938+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-03-13T18:35:15.944+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-03-13T18:35:15.945+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-13T18:35:15.954+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-12 00:00:00+00:00
[2024-03-13T18:35:15.959+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-03-13T18:35:15.961+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpu4ojjcb2']
[2024-03-13T18:35:15.963+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask inaccurate
[2024-03-13T18:35:16.000+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2024-03-12T00:00:00+00:00 [running]> on host b58d4254a693
[2024-03-13T18:35:16.068+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-03-13T18:35:16.071+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-13T18:35:16.072+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'inaccurate'"]
[2024-03-13T18:35:16.086+0000] {subprocess.py:86} INFO - Output:
[2024-03-13T18:35:16.089+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-13T18:35:16.089+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-13T18:35:16.111+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240312T000000, start_date=20240313T183515, end_date=20240313T183516
[2024-03-13T18:35:16.140+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T18:35:16.163+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
