[2024-03-13T18:35:18.289+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:35:09.014559+00:00 [queued]>
[2024-03-13T18:35:18.295+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-03-13T18:35:09.014559+00:00 [queued]>
[2024-03-13T18:35:18.296+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-13T18:35:18.304+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-03-13 18:35:09.014559+00:00
[2024-03-13T18:35:18.309+0000] {standard_task_runner.py:60} INFO - Started process 120 to run task
[2024-03-13T18:35:18.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-03-13T18:35:09.014559+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwt5e1orl']
[2024-03-13T18:35:18.315+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask inaccurate
[2024-03-13T18:35:18.349+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-03-13T18:35:09.014559+00:00 [running]> on host b58d4254a693
[2024-03-13T18:35:18.410+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T18:35:09.014559+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T18:35:09.014559+00:00'
[2024-03-13T18:35:18.413+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-13T18:35:18.414+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'inaccurate'"]
[2024-03-13T18:35:18.426+0000] {subprocess.py:86} INFO - Output:
[2024-03-13T18:35:18.428+0000] {subprocess.py:93} INFO - inaccurate
[2024-03-13T18:35:18.428+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-13T18:35:18.451+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20240313T183509, start_date=20240313T183518, end_date=20240313T183518
[2024-03-13T18:35:18.490+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T18:35:18.514+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
